---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-testservice-deploy
  labels:
    name: dapr-testservice-deploy
    app: dapr-testservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dapr-testservice-pod
      app: dapr-testservice-app
  template:
    metadata:
      name: dapr-testservice-pod
      labels:
        name: dapr-testservice-pod
        app: dapr-testservice-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-testservice-app"
        dapr.io/app-port: "12568"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: dapr-testservice-container
        image: 343192457610.dkr.ecr.ap-south-1.amazonaws.com/daprtestservice-images:daprtestservice-${IMAGE_TAG}
        ports:
        - containerPort: 12568