---
apiVersion: v1
kind: Service
metadata:
  name: dapr-testservice
  labels:
    name: dapr-testservice
    app: dapr-testservice-app
spec:
  type: NodePort
  ports:
  - targetPort: 12568
    port: 80
    nodePort: 30007
  selector:
    name: dapr-testservice-pod
    app: dapr-testservice-app