---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
  labels:
    app: dapr-testservice-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
      #endpointAddress: "http://3.111.22.106:9411/api/v2/spans"
  metrics:
    enabled: false