---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
  #labels:
    #app: login-service-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
      #endpointAddress: "http://3.111.22.106:9411/api/v2/spans"
  mtls:
    enabled:  true
    workloadCertTTL:  24h
    allowedClockSkew:  15m
  #metrics:
    #enabled: true