---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    name: login-service
    app: login-service-app
spec:
  type: NodePort
  ports:
  - targetPort: 14127
    port: 80
    nodePort: 30006
  selector:
    name: login-service-pod
    app: login-service-app