name: CodeQL Bundle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codeql-analysis:
    name: Create CodeQL Bundle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: CodeQL Bundle
      uses: advanced-security/codeql-bundle-action@v1.1.0
      with:
        bundle-version: 'latest'  # Set a specific version or use 'latest'
        packs: 'codeql/javascript-queries,codeql/python-queries'  # Specify the packs you want to include
        workspace: '.'  # Specify the root directory (default is '.')
        upload: true  # Set to true to upload the bundle
        token: ${{ secrets.GITHUB_TOKEN }}  # Use your GitHub token for authentication
        concurrency-limit: 2  # Set the concurrency limit
