            - name: CodeQL Scan Action
  # You may pin to the exact commit or the version.
  # uses: tonys-code-base/run-codeql-analysis-action@775b3f1cc0b55a35e53f2b0f32363c4c7e3984f7
  uses: tonys-code-base/run-codeql-analysis-action@v0.1.0
  with:
    # Git ref to be analyzed
    git_ref: # optional, default is ${{ github.ref }}
    # Commit SHA
    commit_sha: # optional, default is ${{ github.sha }}
    # The source language(s) to carry out the scan against. Example, - to scan for a single language (such as python): "python". - to scan multiple languages (such as python and javascript): "python,javascript" 
    language_to_scan: 
    # GitHub token
    token: 
    # Query suite to use for the analysis https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-analyze#querysuitepack 
    codeql_scan_type: # optional, default is code-scanning
    # Build mode to use for creating the CodeQL DB. Used for compiled languages https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-create#--build-modemode 
    build_mode: # optional, default is 
    # Used for compiled languages. Build command or script that invokes the build process for the codebase https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-create#-c---commandcommand 
    build_command: # optional, default is 
    # Path to CodeQL code scanning configuration file https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-create#--codescanning-configfile 
    codeql_config_file: # optional, default is 
          
